name: parquet_airflow

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.0-python3.11
  user: "50000:0"
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # 1. A Lista de Compras do Python ajustada para a nossa necessidade
    _PIP_ADDITIONAL_REQUIREMENTS: 'pandas pyarrow pymongo python-dotenv'
    PYTHONPATH: "/opt/airflow"
  # 2. Ponte de comunicação com o seu WSL (Crucial para achar o MongoDB)
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    # 3. Mapeamento da nossa estrutura exata de pastas
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./data:/opt/airflow/data    # Onde os Parquets serão salvos
    - ./utils:/opt/airflow/utils  # Onde os seus scripts moram
    - ./.env:/opt/airflow/.env
  depends_on:
    postgres:
      condition: service_healthy

services:
  # O cérebro do Airflow (Guarda o status das DAGs)
  postgres:
    image: postgres:15
    container_name: airflow_postgres_parquet
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    restart: always

  # Inicializador (Prepara o terreno na primeira vez que rodar)
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init_parquet
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      _PIP_ADDITIONAL_REQUIREMENTS: ''  
    user: "0:0"

  # Interface Gráfica (localhost:8080)
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver_parquet
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  # O Motor de Execução (O seu "Mordomo")
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler_parquet
    command: scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

volumes:
  postgres_airflow_data: